version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

  backend:
    image: your-backend-image:latest  # Replace with the actual image name
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - redis

networks:
  my-network:
    driver: bridge
